services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04 # 2025 has issues with healthcheck
    container_name: sql_server_hub
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_webhook_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=database;Database=NotificationHub;User Id=sa;Password=${DB_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - database

volumes:
  mssql_data:

