name: Broadcast Webhook to Local Stack

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send JSON Payload to API via Pinggy
        env:
          TARGET_URL: ${{ secrets.PINGGY_URL }}/webhook
        run: |
          curl -X POST "$TARGET_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "Author": "${{ github.actor }}",
            "Message": "${{ github.event.head_commit.message }}"
          }'
